#!/usr/bin/env python3
"""Generate translated mancala.ftl files for all locales."""

from pathlib import Path

LOCALES_DIR = Path(__file__).parent.parent / "locales"

# fmt: off
TRANSLATIONS = {
"ar": {
    "game-name": "مانكالا",
    "pit-label": 'حفرة { $pit }: { $stones } حجر',
    "sow": '{ $player } يزرع { $stones } حجر من الحفرة { $pit }',
    "capture": '{ $player } يأسر { $captured } حجر!',
    "extra-turn": 'آخر حجر في المخزن! { $player } يحصل على دور إضافي.',
    "winner": '{ $player } يفوز بـ { $score } حجر!',
    "draw": 'تعادل! كلا اللاعبين لديهما { $score } حجر.',
    "board-status": 'حفرك: { $own_pits }. مخزنك: { $own_store }. حفر الخصم: { $opp_pits }. مخزن الخصم: { $opp_store }.',
    "set-stones": 'أحجار لكل حفرة: { $stones }',
    "desc-stones": "عدد الأحجار في كل حفرة في البداية",
    "enter-stones": "أدخل عدد الأحجار الابتدائية لكل حفرة:",
    "option-changed-stones": 'تم تغيير الأحجار الابتدائية إلى { $stones }',
    "pit-empty": "هذه الحفرة فارغة.",
    "final-score": '{ $player }: { $score } حجر',
    "rules": "مانكالا هي لعبة حفر وأحجار للاعبين اثنين.\nكل لاعب لديه 6 حفر ومخزن.\nفي دورك، اختر حفرة من حفرك لتزرع منها.\nتوزع الأحجار واحدة تلو الأخرى في كل حفرة حول اللوحة، بما في ذلك مخزنك ولكن مع تخطي مخزن خصمك.\nإذا سقط آخر حجر في مخزنك، تحصل على دور إضافي.\nإذا سقط آخر حجر في حفرة فارغة في جانبك، تأسر ذلك الحجر وجميع الأحجار في الحفرة المقابلة.\nتنتهي اللعبة عندما يكون جانب أحد اللاعبين فارغاً تماماً. الأحجار المتبقية تذهب إلى مخزن ذلك اللاعب.\nاللاعب الذي لديه أكثر أحجار يفوز.\nاستخدم المفاتيح 1 إلى 6 لاختيار حفرة. اضغط E لفحص اللوحة.",
},
"cs": {
    "game-name": "Mankala",
    "pit-label": 'Jamka { $pit }: { $stones } kamenů',
    "sow": '{ $player } rozsévá { $stones } kamenů z jamky { $pit }',
    "capture": '{ $player } zajímá { $captured } kamenů!',
    "extra-turn": 'Poslední kámen v zásobníku! { $player } hraje znovu.',
    "winner": '{ $player } vyhrává s { $score } kameny!',
    "draw": 'Remíza! Oba hráči mají { $score } kamenů.',
    "board-status": 'Vaše jamky: { $own_pits }. Váš zásobník: { $own_store }. Jamky soupeře: { $opp_pits }. Zásobník soupeře: { $opp_store }.',
    "set-stones": 'Kamenů na jamku: { $stones }',
    "desc-stones": "Počet kamenů v každé jamce na začátku",
    "enter-stones": "Zadejte počet počátečních kamenů na jamku:",
    "option-changed-stones": 'Počáteční kameny změněny na { $stones }',
    "pit-empty": "Tato jamka je prázdná.",
    "final-score": '{ $player }: { $score } kamenů',
    "rules": "Mankala je hra pro dva hráče s jamkami a kameny.\nKaždý hráč má 6 jamek a zásobník.\nNa tahu si vyberte jednu ze svých jamek.\nKameny se rozkládají po jednom do každé jamky kolem desky, včetně vašeho zásobníku, ale přeskakujete zásobník soupeře.\nPokud váš poslední kámen padne do vašeho zásobníku, hrajete znovu.\nPokud váš poslední kámen padne do prázdné jamky na vaší straně, zajmete tento kámen a všechny kameny v protější jamce.\nHra končí, když je jedna strana zcela prázdná. Zbývající kameny jdou do zásobníku toho hráče.\nHráč s nejvíce kameny vyhrává.\nPoužijte klávesy 1 až 6 pro výběr jamky. Stiskněte E pro kontrolu desky.",
},
"de": {
    "game-name": "Mancala",
    "pit-label": 'Mulde { $pit }: { $stones } Steine',
    "sow": '{ $player } sät { $stones } Steine aus Mulde { $pit }',
    "capture": '{ $player } erbeutet { $captured } Steine!',
    "extra-turn": 'Letzter Stein im Speicher! { $player } ist nochmal dran.',
    "winner": '{ $player } gewinnt mit { $score } Steinen!',
    "draw": 'Unentschieden! Beide Spieler haben { $score } Steine.',
    "board-status": 'Deine Mulden: { $own_pits }. Dein Speicher: { $own_store }. Mulden des Gegners: { $opp_pits }. Speicher des Gegners: { $opp_store }.',
    "set-stones": 'Steine pro Mulde: { $stones }',
    "desc-stones": "Anzahl der Steine in jeder Mulde zu Beginn",
    "enter-stones": "Gib die Anzahl der Startsteine pro Mulde ein:",
    "option-changed-stones": 'Startsteine auf { $stones } geändert',
    "pit-empty": "Diese Mulde ist leer.",
    "final-score": '{ $player }: { $score } Steine',
    "rules": "Mancala ist ein Mulden- und Steinspiel für zwei Spieler.\nJeder Spieler hat 6 Mulden und einen Speicher.\nWähle in deinem Zug eine deiner Mulden zum Säen.\nSteine werden einzeln in jede Mulde rund um das Brett gelegt, einschließlich deines Speichers, aber der Speicher des Gegners wird übersprungen.\nLandet dein letzter Stein in deinem Speicher, bist du nochmal dran.\nLandet dein letzter Stein in einer leeren Mulde auf deiner Seite, erbeutest du diesen Stein und alle Steine in der gegenüberliegenden Mulde.\nDas Spiel endet, wenn eine Seite komplett leer ist. Verbleibende Steine gehen in den Speicher des jeweiligen Spielers.\nDer Spieler mit den meisten Steinen gewinnt.\nBenutze die Tasten 1 bis 6 um eine Mulde zu wählen. Drücke E um das Brett zu prüfen.",
},
"es": {
    "game-name": "Mancala",
    "pit-label": 'Hoyo { $pit }: { $stones } piedras',
    "sow": '{ $player } siembra { $stones } piedras del hoyo { $pit }',
    "capture": '¡{ $player } captura { $captured } piedras!',
    "extra-turn": '¡Última piedra en el almacén! { $player } tiene otro turno.',
    "winner": '¡{ $player } gana con { $score } piedras!',
    "draw": '¡Empate! Ambos jugadores tienen { $score } piedras.',
    "board-status": 'Tus hoyos: { $own_pits }. Tu almacén: { $own_store }. Hoyos del oponente: { $opp_pits }. Almacén del oponente: { $opp_store }.',
    "set-stones": 'Piedras por hoyo: { $stones }',
    "desc-stones": "Número de piedras en cada hoyo al inicio",
    "enter-stones": "Ingresa el número de piedras iniciales por hoyo:",
    "option-changed-stones": 'Piedras iniciales cambiadas a { $stones }',
    "pit-empty": "Ese hoyo está vacío.",
    "final-score": '{ $player }: { $score } piedras',
    "rules": "Mancala es un juego de hoyos y piedras para dos jugadores.\nCada jugador tiene 6 hoyos y un almacén.\nEn tu turno, elige uno de tus hoyos para sembrar.\nLas piedras se colocan una por una en cada hoyo alrededor del tablero, incluyendo tu almacén pero saltando el del oponente.\nSi tu última piedra cae en tu almacén, tienes otro turno.\nSi tu última piedra cae en un hoyo vacío de tu lado, capturas esa piedra y todas las del hoyo opuesto.\nEl juego termina cuando un lado está completamente vacío. Las piedras restantes van al almacén de ese jugador.\nEl jugador con más piedras gana.\nUsa las teclas 1 a 6 para elegir un hoyo. Presiona E para revisar el tablero.",
},
"fa": {
    "game-name": "منقله",
    "pit-label": 'چاله { $pit }: { $stones } سنگ',
    "sow": '{ $player } { $stones } سنگ از چاله { $pit } می‌کارد',
    "capture": '{ $player } { $captured } سنگ گرفت!',
    "extra-turn": 'آخرین سنگ در انبار! { $player } نوبت اضافی دارد.',
    "winner": '{ $player } با { $score } سنگ برنده شد!',
    "draw": 'مساوی! هر دو بازیکن { $score } سنگ دارند.',
    "board-status": 'چاله‌های شما: { $own_pits }. انبار شما: { $own_store }. چاله‌های حریف: { $opp_pits }. انبار حریف: { $opp_store }.',
    "set-stones": 'سنگ در هر چاله: { $stones }',
    "desc-stones": "تعداد سنگ‌ها در هر چاله در شروع",
    "enter-stones": "تعداد سنگ‌های اولیه هر چاله را وارد کنید:",
    "option-changed-stones": 'سنگ‌های اولیه به { $stones } تغییر کرد',
    "pit-empty": "این چاله خالی است.",
    "final-score": '{ $player }: { $score } سنگ',
    "rules": "منقله یک بازی دو نفره با چاله و سنگ است.\nهر بازیکن ۶ چاله و یک انبار دارد.\nدر نوبت خود، یکی از چاله‌هایتان را برای کاشتن انتخاب کنید.\nسنگ‌ها یکی یکی در هر چاله دور تخته قرار می‌گیرند، شامل انبار شما اما با رد شدن از انبار حریف.\nاگر آخرین سنگ در انبار شما بیفتد، نوبت اضافی می‌گیرید.\nاگر آخرین سنگ در چاله خالی سمت شما بیفتد، آن سنگ و تمام سنگ‌های چاله مقابل را می‌گیرید.\nبازی زمانی تمام می‌شود که یک طرف کاملاً خالی باشد.\nبازیکنی که سنگ بیشتری دارد برنده است.\nاز کلیدهای ۱ تا ۶ برای انتخاب چاله استفاده کنید. E را برای بررسی تخته فشار دهید.",
},
"fr": {
    "game-name": "Mancala",
    "pit-label": 'Trou { $pit } : { $stones } graines',
    "sow": '{ $player } sème { $stones } graines du trou { $pit }',
    "capture": '{ $player } capture { $captured } graines !',
    "extra-turn": 'Dernière graine dans le grenier ! { $player } rejoue.',
    "winner": '{ $player } gagne avec { $score } graines !',
    "draw": 'Égalité ! Les deux joueurs ont { $score } graines.',
    "board-status": 'Vos trous : { $own_pits }. Votre grenier : { $own_store }. Trous adverses : { $opp_pits }. Grenier adverse : { $opp_store }.',
    "set-stones": 'Graines par trou : { $stones }',
    "desc-stones": "Nombre de graines dans chaque trou au début",
    "enter-stones": "Entrez le nombre de graines de départ par trou :",
    "option-changed-stones": 'Graines de départ changées à { $stones }',
    "pit-empty": "Ce trou est vide.",
    "final-score": '{ $player } : { $score } graines',
    "rules": "Le Mancala est un jeu de trous et de graines pour deux joueurs.\nChaque joueur a 6 trous et un grenier.\nÀ votre tour, choisissez un de vos trous pour semer.\nLes graines sont déposées une par une dans chaque trou autour du plateau, y compris votre grenier mais en sautant celui de l'adversaire.\nSi votre dernière graine tombe dans votre grenier, vous rejouez.\nSi votre dernière graine tombe dans un trou vide de votre côté, vous capturez cette graine et toutes celles du trou opposé.\nLa partie se termine quand un côté est complètement vide. Les graines restantes vont dans le grenier du joueur correspondant.\nLe joueur avec le plus de graines gagne.\nUtilisez les touches 1 à 6 pour choisir un trou. Appuyez sur E pour vérifier le plateau.",
},
"hi": {
    "game-name": "मंकाला",
    "pit-label": 'गड्ढा { $pit }: { $stones } पत्थर',
    "sow": '{ $player } गड्ढे { $pit } से { $stones } पत्थर बोता है',
    "capture": '{ $player } ने { $captured } पत्थर पकड़े!',
    "extra-turn": 'आखिरी पत्थर भंडार में! { $player } को एक और बारी मिलती है।',
    "winner": '{ $player } { $score } पत्थरों से जीता!',
    "draw": 'बराबरी! दोनों खिलाड़ियों के पास { $score } पत्थर हैं।',
    "board-status": 'आपके गड्ढे: { $own_pits }। आपका भंडार: { $own_store }। प्रतिद्वंद्वी के गड्ढे: { $opp_pits }। प्रतिद्वंद्वी का भंडार: { $opp_store }।',
    "set-stones": 'प्रति गड्ढा पत्थर: { $stones }',
    "desc-stones": "शुरुआत में हर गड्ढे में पत्थरों की संख्या",
    "enter-stones": "प्रति गड्ढा शुरुआती पत्थरों की संख्या दर्ज करें:",
    "option-changed-stones": 'शुरुआती पत्थर { $stones } में बदले गए',
    "pit-empty": "वह गड्ढा खाली है।",
    "final-score": '{ $player }: { $score } पत्थर',
    "rules": "मंकाला दो खिलाड़ियों का गड्ढे और पत्थर का खेल है।\nहर खिलाड़ी के पास 6 गड्ढे और एक भंडार होता है।\nअपनी बारी में, बोने के लिए अपना एक गड्ढा चुनें।\nपत्थर बोर्ड के चारों ओर हर गड्ढे में एक-एक करके रखे जाते हैं, आपके भंडार सहित लेकिन प्रतिद्वंद्वी के भंडार को छोड़कर।\nअगर आपका आखिरी पत्थर आपके भंडार में गिरता है, तो आपको एक और बारी मिलती है।\nअगर आपका आखिरी पत्थर आपकी तरफ के खाली गड्ढे में गिरता है, तो आप वह पत्थर और सामने के गड्ढे के सभी पत्थर पकड़ लेते हैं।\nखेल तब समाप्त होता है जब एक तरफ पूरी तरह खाली हो जाती है।\nसबसे ज्यादा पत्थरों वाला खिलाड़ी जीतता है।\nगड्ढा चुनने के लिए 1 से 6 कुंजियों का उपयोग करें। बोर्ड जांचने के लिए E दबाएं।",
},
"hr": {
    "game-name": "Mankala",
    "pit-label": 'Rupa { $pit }: { $stones } kamenčića',
    "sow": '{ $player } sije { $stones } kamenčića iz rupe { $pit }',
    "capture": '{ $player } zarobljava { $captured } kamenčića!',
    "extra-turn": 'Zadnji kamenčić u spremištu! { $player } igra ponovo.',
    "winner": '{ $player } pobjeđuje s { $score } kamenčića!',
    "draw": 'Neriješeno! Oba igrača imaju { $score } kamenčića.',
    "board-status": 'Vaše rupe: { $own_pits }. Vaše spremište: { $own_store }. Protivnikove rupe: { $opp_pits }. Protivnikovo spremište: { $opp_store }.',
    "set-stones": 'Kamenčića po rupi: { $stones }',
    "desc-stones": "Broj kamenčića u svakoj rupi na početku",
    "enter-stones": "Unesite broj početnih kamenčića po rupi:",
    "option-changed-stones": 'Početni kamenčići promijenjeni na { $stones }',
    "pit-empty": "Ta rupa je prazna.",
    "final-score": '{ $player }: { $score } kamenčića',
    "rules": "Mankala je igra za dva igrača s rupama i kamenčićima.\nSvaki igrač ima 6 rupa i spremište.\nNa svom potezu odaberite jednu od svojih rupa za sijanje.\nKamenčići se stavljaju jedan po jedan u svaku rupu oko ploče, uključujući vaše spremište ali preskačući protivnikovo.\nAko vaš zadnji kamenčić padne u vaše spremište, igrate ponovo.\nAko vaš zadnji kamenčić padne u praznu rupu na vašoj strani, zarobljavate taj kamenčić i sve kamenčiće iz suprotne rupe.\nIgra završava kad je jedna strana potpuno prazna.\nIgrač s najviše kamenčića pobjeđuje.\nKoristite tipke 1 do 6 za odabir rupe. Pritisnite E za provjeru ploče.",
},
"hu": {
    "game-name": "Mankala",
    "pit-label": '{ $pit }. gödör: { $stones } kő',
    "sow": '{ $player } { $stones } követ vet a { $pit }. gödörből',
    "capture": '{ $player } elfog { $captured } követ!',
    "extra-turn": 'Utolsó kő a tárban! { $player } újra jön.',
    "winner": '{ $player } nyer { $score } kővel!',
    "draw": 'Döntetlen! Mindkét játékosnak { $score } köve van.',
    "board-status": 'Gödreid: { $own_pits }. Tárad: { $own_store }. Ellenfél gödrei: { $opp_pits }. Ellenfél tára: { $opp_store }.',
    "set-stones": 'Kő gödrönként: { $stones }',
    "desc-stones": "Kövek száma minden gödörben az elején",
    "enter-stones": "Add meg a kezdő kövek számát gödrönként:",
    "option-changed-stones": 'Kezdő kövek { $stones }-ra módosítva',
    "pit-empty": "Ez a gödör üres.",
    "final-score": '{ $player }: { $score } kő',
    "rules": "A Mankala kétszemélyes gödör- és kőjáték.\nMinden játékosnak 6 gödre és egy tára van.\nA lépésedben válassz egy gödröt a vetéshez.\nA köveket egyenként helyezed el a gödrökbe a tábla körül, beleértve a táradat, de kihagyva az ellenfél tárát.\nHa az utolsó köved a táradba esik, újra te jössz.\nHa az utolsó köved a te oldaladon egy üres gödörbe esik, elfogod azt a követ és a szemben lévő gödör összes kövét.\nA játék véget ér, ha az egyik oldal teljesen üres.\nA legtöbb kővel rendelkező játékos nyer.\nHasználd az 1-6 billentyűket a gödör kiválasztásához. Nyomd meg az E-t a tábla ellenőrzéséhez.",
},
"id": {
    "game-name": "Congklak",
    "pit-label": 'Lubang { $pit }: { $stones } biji',
    "sow": '{ $player } menabur { $stones } biji dari lubang { $pit }',
    "capture": '{ $player } menangkap { $captured } biji!',
    "extra-turn": 'Biji terakhir di lumbung! { $player } mendapat giliran tambahan.',
    "winner": '{ $player } menang dengan { $score } biji!',
    "draw": 'Seri! Kedua pemain memiliki { $score } biji.',
    "board-status": 'Lubang Anda: { $own_pits }. Lumbung Anda: { $own_store }. Lubang lawan: { $opp_pits }. Lumbung lawan: { $opp_store }.',
    "set-stones": 'Biji per lubang: { $stones }',
    "desc-stones": "Jumlah biji di setiap lubang saat mulai",
    "enter-stones": "Masukkan jumlah biji awal per lubang:",
    "option-changed-stones": 'Biji awal diubah menjadi { $stones }',
    "pit-empty": "Lubang itu kosong.",
    "final-score": '{ $player }: { $score } biji',
    "rules": "Congklak adalah permainan lubang dan biji untuk dua pemain.\nSetiap pemain memiliki 6 lubang dan satu lumbung.\nPada giliran Anda, pilih salah satu lubang untuk menabur.\nBiji dijatuhkan satu per satu ke setiap lubang di sekeliling papan, termasuk lumbung Anda tapi melewati lumbung lawan.\nJika biji terakhir jatuh di lumbung Anda, Anda mendapat giliran tambahan.\nJika biji terakhir jatuh di lubang kosong di sisi Anda, Anda menangkap biji itu dan semua biji di lubang seberang.\nPermainan berakhir ketika satu sisi benar-benar kosong.\nPemain dengan biji terbanyak menang.\nGunakan tombol 1 sampai 6 untuk memilih lubang. Tekan E untuk memeriksa papan.",
},
"it": {
    "game-name": "Mancala",
    "pit-label": 'Buca { $pit }: { $stones } semi',
    "sow": '{ $player } semina { $stones } semi dalla buca { $pit }',
    "capture": '{ $player } cattura { $captured } semi!',
    "extra-turn": "Ultimo seme nel deposito! { $player } ha un altro turno.",
    "winner": '{ $player } vince con { $score } semi!',
    "draw": 'Pareggio! Entrambi i giocatori hanno { $score } semi.',
    "board-status": 'Le tue buche: { $own_pits }. Il tuo deposito: { $own_store }. Buche avversarie: { $opp_pits }. Deposito avversario: { $opp_store }.',
    "set-stones": 'Semi per buca: { $stones }',
    "desc-stones": "Numero di semi in ogni buca all'inizio",
    "enter-stones": "Inserisci il numero di semi iniziali per buca:",
    "option-changed-stones": 'Semi iniziali cambiati a { $stones }',
    "pit-empty": "Quella buca è vuota.",
    "final-score": '{ $player }: { $score } semi',
    "rules": "Il Mancala è un gioco di buche e semi per due giocatori.\nOgni giocatore ha 6 buche e un deposito.\nNel tuo turno, scegli una delle tue buche per seminare.\nI semi vengono depositati uno per uno in ogni buca intorno al tavoliere, incluso il tuo deposito ma saltando quello dell'avversario.\nSe l'ultimo seme cade nel tuo deposito, hai un altro turno.\nSe l'ultimo seme cade in una buca vuota dalla tua parte, catturi quel seme e tutti i semi nella buca opposta.\nIl gioco finisce quando un lato è completamente vuoto.\nIl giocatore con più semi vince.\nUsa i tasti da 1 a 6 per scegliere una buca. Premi E per controllare il tavoliere.",
},
"ja": {
    "game-name": "マンカラ",
    "pit-label": 'ポケット{ $pit }：石{ $stones }個',
    "sow": '{ $player }がポケット{ $pit }から石{ $stones }個を蒔きます',
    "capture": '{ $player }が石{ $captured }個を獲得！',
    "extra-turn": '最後の石がストアに！{ $player }はもう一度プレイできます。',
    "winner": '{ $player }が石{ $score }個で勝利！',
    "draw": '引き分け！両プレイヤーとも石{ $score }個です。',
    "board-status": 'あなたのポケット：{ $own_pits }。あなたのストア：{ $own_store }。相手のポケット：{ $opp_pits }。相手のストア：{ $opp_store }。',
    "set-stones": 'ポケットあたりの石：{ $stones }',
    "desc-stones": "開始時の各ポケットの石の数",
    "enter-stones": "ポケットあたりの初期石数を入力：",
    "option-changed-stones": '初期石数が{ $stones }に変更されました',
    "pit-empty": "そのポケットは空です。",
    "final-score": '{ $player }：石{ $score }個',
    "rules": "マンカラは2人用のポケットと石のゲームです。\n各プレイヤーは6つのポケットと1つのストアを持ちます。\n自分のターンで、蒔くポケットを1つ選びます。\n石はボードの各ポケットに1つずつ置かれます。自分のストアには入れますが、相手のストアは飛ばします。\n最後の石が自分のストアに入ったら、もう一度プレイできます。\n最後の石が自分側の空のポケットに入ったら、その石と向かいのポケットの石をすべて獲得します。\n片側が完全に空になったらゲーム終了です。\n石が最も多いプレイヤーの勝ちです。\nキー1〜6でポケットを選択。Eでボードを確認。",
},
"ko": {
    "game-name": "만칼라",
    "pit-label": '구멍 { $pit }: 돌 { $stones }개',
    "sow": '{ $player }이(가) 구멍 { $pit }에서 돌 { $stones }개를 뿌립니다',
    "capture": '{ $player }이(가) 돌 { $captured }개를 획득!',
    "extra-turn": '마지막 돌이 창고에! { $player }이(가) 추가 턴을 얻습니다.',
    "winner": '{ $player }이(가) 돌 { $score }개로 승리!',
    "draw": '무승부! 양쪽 모두 돌 { $score }개입니다.',
    "board-status": '내 구멍: { $own_pits }. 내 창고: { $own_store }. 상대 구멍: { $opp_pits }. 상대 창고: { $opp_store }.',
    "set-stones": '구멍당 돌: { $stones }',
    "desc-stones": "시작 시 각 구멍의 돌 수",
    "enter-stones": "구멍당 시작 돌 수를 입력하세요:",
    "option-changed-stones": '시작 돌이 { $stones }(으)로 변경됨',
    "pit-empty": "그 구멍은 비어 있습니다.",
    "final-score": '{ $player }: 돌 { $score }개',
    "rules": "만칼라는 2인용 구멍과 돌 게임입니다.\n각 플레이어는 6개의 구멍과 1개의 창고를 가집니다.\n자신의 턴에 뿌릴 구멍 하나를 선택합니다.\n돌은 보드를 돌며 각 구멍에 하나씩 놓입니다. 자신의 창고에는 넣지만 상대 창고는 건너뜁니다.\n마지막 돌이 자신의 창고에 들어가면 추가 턴을 얻습니다.\n마지막 돌이 자기 쪽 빈 구멍에 들어가면 그 돌과 맞은편 구멍의 모든 돌을 획득합니다.\n한쪽이 완전히 비면 게임이 끝납니다.\n돌이 가장 많은 플레이어가 승리합니다.\n1~6 키로 구멍을 선택하세요. E를 눌러 보드를 확인하세요.",
},
"mn": {
    "game-name": "Манкала",
    "pit-label": 'Нүх { $pit }: { $stones } чулуу',
    "sow": '{ $player } { $pit }-р нүхнээс { $stones } чулуу тарина',
    "capture": '{ $player } { $captured } чулуу барьлав!',
    "extra-turn": 'Сүүлийн чулуу агуулахад! { $player } дахин тоглоно.',
    "winner": '{ $player } { $score } чулуугаар ялав!',
    "draw": 'Тэнцэв! Хоёр тоглогч тус бүр { $score } чулуутай.',
    "board-status": 'Таны нүхнүүд: { $own_pits }. Таны агуулах: { $own_store }. Өрсөлдөгчийн нүхнүүд: { $opp_pits }. Өрсөлдөгчийн агуулах: { $opp_store }.',
    "set-stones": 'Нүх тус бүрийн чулуу: { $stones }',
    "desc-stones": "Эхлэхэд нүх бүрт байх чулууны тоо",
    "enter-stones": "Нүх тус бүрийн эхлэл чулууны тоог оруулна уу:",
    "option-changed-stones": 'Эхлэл чулуу { $stones } болж өөрчлөгдлөө',
    "pit-empty": "Тэр нүх хоосон байна.",
    "final-score": '{ $player }: { $score } чулуу',
    "rules": "Манкала бол хоёр тоглогчийн нүх ба чулууны тоглоом юм.\nТоглогч бүр 6 нүх, 1 агуулахтай.\nЭэлжиндээ тарих нүхээ сонгоно.\nЧулууг самбар дагуу нүх бүрт нэг нэгээр тавина, агуулахдаа тавьж болох ч өрсөлдөгчийн агуулахыг алгасна.\nСүүлийн чулуу агуулахад орвол дахин тоглоно.\nСүүлийн чулуу өөрийн тал дахь хоосон нүхэнд орвол тэр чулуу болон эсрэг талын бүх чулууг авна.\nНэг тал бүрэн хоосорвол тоглоом дуусна.\nХамгийн олон чулуутай тоглогч ялна.\n1-6 товчлуураар нүх сонгоно. E дарж самбарыг шалгана.",
},
"nl": {
    "game-name": "Mancala",
    "pit-label": 'Put { $pit }: { $stones } stenen',
    "sow": '{ $player } zaait { $stones } stenen uit put { $pit }',
    "capture": '{ $player } vangt { $captured } stenen!',
    "extra-turn": 'Laatste steen in de pot! { $player } is opnieuw aan de beurt.',
    "winner": '{ $player } wint met { $score } stenen!',
    "draw": 'Gelijkspel! Beide spelers hebben { $score } stenen.',
    "board-status": 'Jouw putten: { $own_pits }. Jouw pot: { $own_store }. Putten tegenstander: { $opp_pits }. Pot tegenstander: { $opp_store }.',
    "set-stones": 'Stenen per put: { $stones }',
    "desc-stones": "Aantal stenen in elke put bij de start",
    "enter-stones": "Voer het aantal startstenen per put in:",
    "option-changed-stones": 'Startstenen gewijzigd naar { $stones }',
    "pit-empty": "Die put is leeg.",
    "final-score": '{ $player }: { $score } stenen',
    "rules": "Mancala is een put-en-stenenspel voor twee spelers.\nElke speler heeft 6 putten en een pot.\nKies in je beurt een van je putten om te zaaien.\nStenen worden één voor één in elke put rondom het bord gelegd, inclusief je pot maar de pot van de tegenstander wordt overgeslagen.\nAls je laatste steen in je pot valt, ben je opnieuw aan de beurt.\nAls je laatste steen in een lege put aan jouw kant valt, vang je die steen en alle stenen in de tegenoverliggende put.\nHet spel eindigt als één kant helemaal leeg is.\nDe speler met de meeste stenen wint.\nGebruik toetsen 1 tot 6 om een put te kiezen. Druk op E om het bord te bekijken.",
},
"pl": {
    "game-name": "Mankala",
    "pit-label": 'Dołek { $pit }: { $stones } kamieni',
    "sow": '{ $player } sieje { $stones } kamieni z dołka { $pit }',
    "capture": '{ $player } przechwytuje { $captured } kamieni!',
    "extra-turn": 'Ostatni kamień w magazynie! { $player } gra ponownie.',
    "winner": '{ $player } wygrywa z { $score } kamieniami!',
    "draw": 'Remis! Obaj gracze mają { $score } kamieni.',
    "board-status": 'Twoje dołki: { $own_pits }. Twój magazyn: { $own_store }. Dołki przeciwnika: { $opp_pits }. Magazyn przeciwnika: { $opp_store }.',
    "set-stones": 'Kamieni na dołek: { $stones }',
    "desc-stones": "Liczba kamieni w każdym dołku na początku",
    "enter-stones": "Podaj liczbę początkowych kamieni na dołek:",
    "option-changed-stones": 'Początkowe kamienie zmienione na { $stones }',
    "pit-empty": "Ten dołek jest pusty.",
    "final-score": '{ $player }: { $score } kamieni',
    "rules": "Mankala to gra w dołki i kamienie dla dwóch graczy.\nKażdy gracz ma 6 dołków i magazyn.\nW swojej turze wybierz jeden z dołków do siania.\nKamienie są kładzione po jednym w każdy dołek dookoła planszy, włącznie z twoim magazynem, ale pomijając magazyn przeciwnika.\nJeśli ostatni kamień wpadnie do twojego magazynu, grasz ponownie.\nJeśli ostatni kamień wpadnie do pustego dołka po twojej stronie, przechwytujesz ten kamień i wszystkie kamienie z przeciwległego dołka.\nGra kończy się, gdy jedna strona jest całkowicie pusta.\nGracz z największą liczbą kamieni wygrywa.\nUżyj klawiszy 1-6 aby wybrać dołek. Naciśnij E aby sprawdzić planszę.",
},
"pt": {
    "game-name": "Mancala",
    "pit-label": 'Cova { $pit }: { $stones } pedras',
    "sow": '{ $player } semeia { $stones } pedras da cova { $pit }',
    "capture": '{ $player } captura { $captured } pedras!',
    "extra-turn": 'Última pedra no depósito! { $player } joga novamente.',
    "winner": '{ $player } vence com { $score } pedras!',
    "draw": 'Empate! Ambos jogadores têm { $score } pedras.',
    "board-status": 'Suas covas: { $own_pits }. Seu depósito: { $own_store }. Covas do oponente: { $opp_pits }. Depósito do oponente: { $opp_store }.',
    "set-stones": 'Pedras por cova: { $stones }',
    "desc-stones": "Número de pedras em cada cova no início",
    "enter-stones": "Digite o número de pedras iniciais por cova:",
    "option-changed-stones": 'Pedras iniciais alteradas para { $stones }',
    "pit-empty": "Essa cova está vazia.",
    "final-score": '{ $player }: { $score } pedras',
    "rules": "Mancala é um jogo de covas e pedras para dois jogadores.\nCada jogador tem 6 covas e um depósito.\nNo seu turno, escolha uma de suas covas para semear.\nAs pedras são colocadas uma a uma em cada cova ao redor do tabuleiro, incluindo seu depósito mas pulando o do oponente.\nSe a última pedra cair no seu depósito, você joga novamente.\nSe a última pedra cair numa cova vazia do seu lado, você captura essa pedra e todas as da cova oposta.\nO jogo termina quando um lado está completamente vazio.\nO jogador com mais pedras vence.\nUse as teclas 1 a 6 para escolher uma cova. Pressione E para verificar o tabuleiro.",
},
"ro": {
    "game-name": "Mancala",
    "pit-label": 'Groapă { $pit }: { $stones } pietre',
    "sow": '{ $player } seamănă { $stones } pietre din groapa { $pit }',
    "capture": '{ $player } capturează { $captured } pietre!',
    "extra-turn": 'Ultima piatră în depozit! { $player } joacă din nou.',
    "winner": '{ $player } câștigă cu { $score } pietre!',
    "draw": 'Egalitate! Ambii jucători au { $score } pietre.',
    "board-status": 'Gropile tale: { $own_pits }. Depozitul tău: { $own_store }. Gropile adversarului: { $opp_pits }. Depozitul adversarului: { $opp_store }.',
    "set-stones": 'Pietre pe groapă: { $stones }',
    "desc-stones": "Numărul de pietre în fiecare groapă la început",
    "enter-stones": "Introduceți numărul de pietre inițiale pe groapă:",
    "option-changed-stones": 'Pietrele inițiale schimbate la { $stones }',
    "pit-empty": "Acea groapă este goală.",
    "final-score": '{ $player }: { $score } pietre',
    "rules": "Mancala este un joc de gropi și pietre pentru doi jucători.\nFiecare jucător are 6 gropi și un depozit.\nLa rândul tău, alege una din gropile tale pentru a semăna.\nPietrele sunt plasate câte una în fiecare groapă din jurul tablei, inclusiv depozitul tău dar sărind depozitul adversarului.\nDacă ultima piatră cade în depozitul tău, joci din nou.\nDacă ultima piatră cade într-o groapă goală de partea ta, capturezi acea piatră și toate pietrele din groapa opusă.\nJocul se termină când o parte este complet goală.\nJucătorul cu cele mai multe pietre câștigă.\nFolosește tastele 1-6 pentru a alege o groapă. Apasă E pentru a verifica tabla.",
},
"ru": {
    "game-name": "Манкала",
    "pit-label": 'Лунка { $pit }: { $stones } камней',
    "sow": '{ $player } сеет { $stones } камней из лунки { $pit }',
    "capture": '{ $player } захватывает { $captured } камней!',
    "extra-turn": 'Последний камень в хранилище! { $player } ходит ещё раз.',
    "winner": '{ $player } побеждает с { $score } камнями!',
    "draw": 'Ничья! У обоих игроков по { $score } камней.',
    "board-status": 'Ваши лунки: { $own_pits }. Ваше хранилище: { $own_store }. Лунки соперника: { $opp_pits }. Хранилище соперника: { $opp_store }.',
    "set-stones": 'Камней на лунку: { $stones }',
    "desc-stones": "Количество камней в каждой лунке в начале",
    "enter-stones": "Введите количество начальных камней на лунку:",
    "option-changed-stones": 'Начальные камни изменены на { $stones }',
    "pit-empty": "Эта лунка пуста.",
    "final-score": '{ $player }: { $score } камней',
    "rules": "Манкала — игра для двух игроков с лунками и камнями.\nУ каждого игрока 6 лунок и хранилище.\nВ свой ход выберите одну из своих лунок для посева.\nКамни раскладываются по одному в каждую лунку вокруг доски, включая ваше хранилище, но пропуская хранилище соперника.\nЕсли последний камень попадает в ваше хранилище, вы ходите ещё раз.\nЕсли последний камень попадает в пустую лунку на вашей стороне, вы захватываете этот камень и все камни из противоположной лунки.\nИгра заканчивается, когда одна сторона полностью пуста.\nПобеждает игрок с наибольшим количеством камней.\nИспользуйте клавиши 1-6 для выбора лунки. Нажмите E для проверки доски.",
},
"sk": {
    "game-name": "Mankala",
    "pit-label": 'Jamka { $pit }: { $stones } kameňov',
    "sow": '{ $player } seje { $stones } kameňov z jamky { $pit }',
    "capture": '{ $player } zajíma { $captured } kameňov!',
    "extra-turn": 'Posledný kameň v zásobníku! { $player } hrá znova.',
    "winner": '{ $player } vyhráva s { $score } kameňmi!',
    "draw": 'Remíza! Obaja hráči majú { $score } kameňov.',
    "board-status": 'Vaše jamky: { $own_pits }. Váš zásobník: { $own_store }. Jamky súpera: { $opp_pits }. Zásobník súpera: { $opp_store }.',
    "set-stones": 'Kameňov na jamku: { $stones }',
    "desc-stones": "Počet kameňov v každej jamke na začiatku",
    "enter-stones": "Zadajte počet počiatočných kameňov na jamku:",
    "option-changed-stones": 'Počiatočné kamene zmenené na { $stones }',
    "pit-empty": "Táto jamka je prázdna.",
    "final-score": '{ $player }: { $score } kameňov',
    "rules": "Mankala je hra pre dvoch hráčov s jamkami a kameňmi.\nKaždý hráč má 6 jamiek a zásobník.\nNa ťahu si vyberte jednu zo svojich jamiek.\nKamene sa rozkladajú po jednom do každej jamky okolo dosky, vrátane vášho zásobníka, ale preskakujete zásobník súpera.\nAk váš posledný kameň padne do vášho zásobníka, hráte znova.\nAk váš posledný kameň padne do prázdnej jamky na vašej strane, zajmete tento kameň a všetky kamene v protiľahlej jamke.\nHra končí, keď je jedna strana úplne prázdna.\nHráč s najviac kameňmi vyhráva.\nPoužite klávesy 1-6 na výber jamky. Stlačte E na kontrolu dosky.",
},
"sl": {
    "game-name": "Mankala",
    "pit-label": 'Luknja { $pit }: { $stones } kamnov',
    "sow": '{ $player } seje { $stones } kamnov iz luknje { $pit }',
    "capture": '{ $player } zajame { $captured } kamnov!',
    "extra-turn": 'Zadnji kamen v shrambi! { $player } igra še enkrat.',
    "winner": '{ $player } zmaga s { $score } kamni!',
    "draw": 'Izenačenje! Oba igralca imata { $score } kamnov.',
    "board-status": 'Vaše luknje: { $own_pits }. Vaša shramba: { $own_store }. Nasprotnikove luknje: { $opp_pits }. Nasprotnikova shramba: { $opp_store }.',
    "set-stones": 'Kamnov na luknjo: { $stones }',
    "desc-stones": "Število kamnov v vsaki luknji na začetku",
    "enter-stones": "Vnesite število začetnih kamnov na luknjo:",
    "option-changed-stones": 'Začetni kamni spremenjeni na { $stones }',
    "pit-empty": "Ta luknja je prazna.",
    "final-score": '{ $player }: { $score } kamnov',
    "rules": "Mankala je igra za dva igralca z luknjami in kamni.\nVsak igralec ima 6 lukenj in shrambo.\nNa svoji potezi izberite eno od svojih lukenj za sejanje.\nKamni se polagajo enega za drugim v vsako luknjo okrog plošče, vključno z vašo shrambo, vendar preskočite nasprotnikovo.\nČe zadnji kamen pade v vašo shrambo, igrate še enkrat.\nČe zadnji kamen pade v prazno luknjo na vaši strani, zajamete ta kamen in vse kamne v nasprotni luknji.\nIgra se konča, ko je ena stran popolnoma prazna.\nIgralec z največ kamni zmaga.\nUporabite tipke 1-6 za izbiro luknje. Pritisnite E za pregled plošče.",
},
"sr": {
    "game-name": "Манкала",
    "pit-label": 'Рупа { $pit }: { $stones } каменчића',
    "sow": '{ $player } сеје { $stones } каменчића из рупе { $pit }',
    "capture": '{ $player } заробљава { $captured } каменчића!',
    "extra-turn": 'Последњи каменчић у спремишту! { $player } игра поново.',
    "winner": '{ $player } побеђује са { $score } каменчића!',
    "draw": 'Нерешено! Оба играча имају { $score } каменчића.',
    "board-status": 'Ваше рупе: { $own_pits }. Ваше спремиште: { $own_store }. Противникове рупе: { $opp_pits }. Противниково спремиште: { $opp_store }.',
    "set-stones": 'Каменчића по рупи: { $stones }',
    "desc-stones": "Број каменчића у свакој рупи на почетку",
    "enter-stones": "Унесите број почетних каменчића по рупи:",
    "option-changed-stones": 'Почетни каменчићи промењени на { $stones }',
    "pit-empty": "Та рупа је празна.",
    "final-score": '{ $player }: { $score } каменчића',
    "rules": "Манкала је игра за два играча са рупама и каменчићима.\nСваки играч има 6 рупа и спремиште.\nНа свом потезу изаберите једну од својих рупа за сејање.\nКаменчићи се стављају један по један у сваку рупу око табле, укључујући ваше спремиште али прескачући противниково.\nАко ваш последњи каменчић падне у ваше спремиште, играте поново.\nАко ваш последњи каменчић падне у празну рупу на вашој страни, заробљавате тај каменчић и све каменчиће из супротне рупе.\nИгра се завршава кад је једна страна потпуно празна.\nИграч са највише каменчића побеђује.\nКористите тастере 1-6 за избор рупе. Притисните E за проверу табле.",
},
"sv": {
    "game-name": "Mancala",
    "pit-label": 'Grop { $pit }: { $stones } stenar',
    "sow": '{ $player } sår { $stones } stenar från grop { $pit }',
    "capture": '{ $player } fångar { $captured } stenar!',
    "extra-turn": 'Sista stenen i magasinet! { $player } spelar igen.',
    "winner": '{ $player } vinner med { $score } stenar!',
    "draw": 'Oavgjort! Båda spelarna har { $score } stenar.',
    "board-status": 'Dina gropar: { $own_pits }. Ditt magasin: { $own_store }. Motståndarens gropar: { $opp_pits }. Motståndarens magasin: { $opp_store }.',
    "set-stones": 'Stenar per grop: { $stones }',
    "desc-stones": "Antal stenar i varje grop vid start",
    "enter-stones": "Ange antal startstenar per grop:",
    "option-changed-stones": 'Startstenar ändrade till { $stones }',
    "pit-empty": "Den gropen är tom.",
    "final-score": '{ $player }: { $score } stenar',
    "rules": "Mancala är ett grop- och stenspel för två spelare.\nVarje spelare har 6 gropar och ett magasin.\nPå din tur, välj en av dina gropar att så från.\nStenar läggs en och en i varje grop runt brädet, inklusive ditt magasin men hoppa över motståndarens.\nOm din sista sten hamnar i ditt magasin får du spela igen.\nOm din sista sten hamnar i en tom grop på din sida fångar du den stenen och alla stenar i den motsatta gropen.\nSpelet slutar när en sida är helt tom.\nSpelaren med flest stenar vinner.\nAnvänd tangenterna 1-6 för att välja grop. Tryck E för att kontrollera brädet.",
},
"th": {
    "game-name": "มังคาลา",
    "pit-label": 'หลุม { $pit }: { $stones } เม็ด',
    "sow": '{ $player } หว่าน { $stones } เม็ดจากหลุม { $pit }',
    "capture": '{ $player } จับ { $captured } เม็ด!',
    "extra-turn": 'เม็ดสุดท้ายลงคลัง! { $player } ได้เล่นอีกครั้ง',
    "winner": '{ $player } ชนะด้วย { $score } เม็ด!',
    "draw": 'เสมอ! ผู้เล่นทั้งสองมี { $score } เม็ด',
    "board-status": 'หลุมของคุณ: { $own_pits } คลังของคุณ: { $own_store } หลุมฝ่ายตรงข้าม: { $opp_pits } คลังฝ่ายตรงข้าม: { $opp_store }',
    "set-stones": 'เม็ดต่อหลุม: { $stones }',
    "desc-stones": "จำนวนเม็ดในแต่ละหลุมตอนเริ่ม",
    "enter-stones": "ใส่จำนวนเม็ดเริ่มต้นต่อหลุม:",
    "option-changed-stones": 'เม็ดเริ่มต้นเปลี่ยนเป็น { $stones }',
    "pit-empty": "หลุมนั้นว่างเปล่า",
    "final-score": '{ $player }: { $score } เม็ด',
    "rules": "มังคาลาเป็นเกมหลุมและเม็ดสำหรับผู้เล่นสองคน\nผู้เล่นแต่ละคนมี 6 หลุมและ 1 คลัง\nในตาของคุณ เลือกหลุมหนึ่งเพื่อหว่าน\nเม็ดจะถูกวางทีละเม็ดในแต่ละหลุมรอบกระดาน รวมคลังของคุณแต่ข้ามคลังฝ่ายตรงข้าม\nถ้าเม็ดสุดท้ายตกในคลังของคุณ คุณได้เล่นอีกครั้ง\nถ้าเม็ดสุดท้ายตกในหลุมว่างฝั่งคุณ คุณจับเม็ดนั้นและเม็ดทั้งหมดในหลุมตรงข้าม\nเกมจบเมื่อฝั่งหนึ่งว่างหมด\nผู้เล่นที่มีเม็ดมากที่สุดชนะ\nใช้ปุ่ม 1-6 เลือกหลุม กด E ตรวจสอบกระดาน",
},
"tr": {
    "game-name": "Mangala",
    "pit-label": 'Çukur { $pit }: { $stones } taş',
    "sow": "{ $player } çukur { $pit }'den { $stones } taş eker",
    "capture": '{ $player } { $captured } taş yakalar!',
    "extra-turn": 'Son taş hazinede! { $player } tekrar oynuyor.',
    "winner": '{ $player } { $score } taşla kazandı!',
    "draw": 'Berabere! İki oyuncunun da { $score } taşı var.',
    "board-status": 'Çukurlarınız: { $own_pits }. Hazineniz: { $own_store }. Rakibin çukurları: { $opp_pits }. Rakibin hazinesi: { $opp_store }.',
    "set-stones": 'Çukur başına taş: { $stones }',
    "desc-stones": "Başlangıçta her çukurdaki taş sayısı",
    "enter-stones": "Çukur başına başlangıç taş sayısını girin:",
    "option-changed-stones": 'Başlangıç taşları { $stones } olarak değiştirildi',
    "pit-empty": "O çukur boş.",
    "final-score": '{ $player }: { $score } taş',
    "rules": "Mangala iki kişilik bir çukur ve taş oyunudur.\nHer oyuncunun 6 çukuru ve bir hazinesi vardır.\nSıranızda ekmek için çukurlarınızdan birini seçin.\nTaşlar tahtanın etrafında her çukura birer birer konulur, hazineniz dahil ama rakibin hazinesi atlanır.\nSon taşınız hazinenize düşerse tekrar oynarsınız.\nSon taşınız kendi tarafınızdaki boş bir çukura düşerse, o taşı ve karşı çukurdaki tüm taşları yakalarsınız.\nBir taraf tamamen boşaldığında oyun biter.\nEn çok taşı olan oyuncu kazanır.\nÇukur seçmek için 1-6 tuşlarını kullanın. Tahtayı kontrol etmek için E'ye basın.",
},
"uk": {
    "game-name": "Манкала",
    "pit-label": 'Лунка { $pit }: { $stones } каменів',
    "sow": '{ $player } сіє { $stones } каменів з лунки { $pit }',
    "capture": '{ $player } захоплює { $captured } каменів!',
    "extra-turn": 'Останній камінь у сховищі! { $player } ходить ще раз.',
    "winner": '{ $player } перемагає з { $score } каменями!',
    "draw": 'Нічия! Обидва гравці мають по { $score } каменів.',
    "board-status": 'Ваші лунки: { $own_pits }. Ваше сховище: { $own_store }. Лунки суперника: { $opp_pits }. Сховище суперника: { $opp_store }.',
    "set-stones": 'Каменів на лунку: { $stones }',
    "desc-stones": "Кількість каменів у кожній лунці на початку",
    "enter-stones": "Введіть кількість початкових каменів на лунку:",
    "option-changed-stones": 'Початкові камені змінено на { $stones }',
    "pit-empty": "Ця лунка порожня.",
    "final-score": '{ $player }: { $score } каменів',
    "rules": "Манкала — гра для двох гравців з лунками та каменями.\nКожен гравець має 6 лунок і сховище.\nНа своєму ходу оберіть одну зі своїх лунок для посіву.\nКамені розкладаються по одному в кожну лунку навколо дошки, включаючи ваше сховище, але пропускаючи сховище суперника.\nЯкщо останній камінь потрапляє у ваше сховище, ви ходите ще раз.\nЯкщо останній камінь потрапляє в порожню лунку на вашій стороні, ви захоплюєте цей камінь і всі камені з протилежної лунки.\nГра закінчується, коли одна сторона повністю порожня.\nГравець з найбільшою кількістю каменів перемагає.\nВикористовуйте клавіші 1-6 для вибору лунки. Натисніть E для перевірки дошки.",
},
"vi": {
    "game-name": "Ô ăn quan",
    "pit-label": 'Ô { $pit }: { $stones } sỏi',
    "sow": '{ $player } rải { $stones } sỏi từ ô { $pit }',
    "capture": '{ $player } bắt được { $captured } sỏi!',
    "extra-turn": 'Sỏi cuối vào kho! { $player } được đi thêm lượt.',
    "winner": '{ $player } thắng với { $score } sỏi!',
    "draw": 'Hòa! Cả hai người chơi đều có { $score } sỏi.',
    "board-status": 'Ô của bạn: { $own_pits }. Kho của bạn: { $own_store }. Ô đối thủ: { $opp_pits }. Kho đối thủ: { $opp_store }.',
    "set-stones": 'Sỏi mỗi ô: { $stones }',
    "desc-stones": "Số sỏi trong mỗi ô lúc bắt đầu",
    "enter-stones": "Nhập số sỏi ban đầu mỗi ô:",
    "option-changed-stones": 'Sỏi ban đầu đổi thành { $stones }',
    "pit-empty": "Ô đó trống.",
    "final-score": '{ $player }: { $score } sỏi',
    "rules": "Ô ăn quan là trò chơi ô và sỏi cho hai người.\nMỗi người chơi có 6 ô và 1 kho.\nĐến lượt bạn, chọn một ô của mình để rải.\nSỏi được đặt từng viên vào mỗi ô quanh bàn, bao gồm kho của bạn nhưng bỏ qua kho đối thủ.\nNếu sỏi cuối rơi vào kho của bạn, bạn được đi thêm lượt.\nNếu sỏi cuối rơi vào ô trống bên bạn, bạn bắt viên sỏi đó và tất cả sỏi ở ô đối diện.\nTrò chơi kết thúc khi một bên hoàn toàn trống.\nNgười chơi có nhiều sỏi nhất thắng.\nDùng phím 1-6 để chọn ô. Nhấn E để xem bàn.",
},
"zh": {
    "game-name": "播棋",
    "pit-label": '坑 { $pit }：{ $stones } 颗石子',
    "sow": '{ $player } 从坑 { $pit } 播种 { $stones } 颗石子',
    "capture": '{ $player } 俘获 { $captured } 颗石子！',
    "extra-turn": '最后一颗石子落入仓库！{ $player } 再来一回合。',
    "winner": '{ $player } 以 { $score } 颗石子获胜！',
    "draw": '平局！双方各有 { $score } 颗石子。',
    "board-status": '你的坑：{ $own_pits }。你的仓库：{ $own_store }。对手的坑：{ $opp_pits }。对手的仓库：{ $opp_store }。',
    "set-stones": '每坑石子数：{ $stones }',
    "desc-stones": "开始时每个坑中的石子数",
    "enter-stones": "输入每坑的初始石子数：",
    "option-changed-stones": '初始石子数已改为 { $stones }',
    "pit-empty": "该坑为空。",
    "final-score": '{ $player }：{ $score } 颗石子',
    "rules": "播棋是一种双人坑洞和石子游戏。\n每位玩家有6个坑和1个仓库。\n轮到你时，选择一个己方的坑进行播种。\n石子沿棋盘逐个放入每个坑中，包括你的仓库，但跳过对手的仓库。\n如果最后一颗石子落入你的仓库，你可以再走一步。\n如果最后一颗石子落入己方空坑，你俘获该石子及对面坑中的所有石子。\n当一方的坑全部清空时游戏结束。\n石子最多的玩家获胜。\n使用按键1-6选择坑位。按E查看棋盘。",
},
"zu": {
    "game-name": "Mancala",
    "pit-label": 'Umgodi { $pit }: amatshe angu-{ $stones }',
    "sow": '{ $player } uhlwanyela amatshe angu-{ $stones } emgodini { $pit }',
    "capture": '{ $player } ubamba amatshe angu-{ $captured }!',
    "extra-turn": 'Itshe lokugcina esitolo! { $player } uthola elinye ithuba.',
    "winner": '{ $player } unqoba ngamatshe angu-{ $score }!',
    "draw": 'Kulingana! Bobabili abadlali banamatshe angu-{ $score }.',
    "board-status": 'Imigodi yakho: { $own_pits }. Isitolo sakho: { $own_store }. Imigodi yomphikisi: { $opp_pits }. Isitolo somphikisi: { $opp_store }.',
    "set-stones": 'Amatshe ngomgodi: { $stones }',
    "desc-stones": "Inani lamatshe kumgodi ngamunye ekuqaleni",
    "enter-stones": "Faka inani lamatshe okuqala ngomgodi:",
    "option-changed-stones": 'Amatshe okuqala ashintshwe aba ngu-{ $stones }',
    "pit-empty": "Lo mgodi awunalutho.",
    "final-score": '{ $player }: amatshe angu-{ $score }',
    "rules": "I-Mancala umdlalo wemigodi namatshe wabadlali ababili.\nUmdlali ngamunye unemigodi eyi-6 nesitolo esisodwa.\nNgethuba lakho, khetha umgodi owodwa ukuze uhlwanyele.\nAmatshe afakwa ngalinye kumgodi ngamunye ebhodini, kufaka isitolo sakho kodwa weqa isitolo somphikisi.\nUma itshe lokugcina liwela esitolo sakho, udlala futhi.\nUma itshe lokugcina liwela emgodini ongenalutho ohlangothini lwakho, ubamba lelo tshe nawo wonke amatshe emgodini obhekene nawo.\nUmdlalo uphela uma uhlangothi olulodwa lungenalutho ngokuphelele.\nUmdlali onamatshe amaningi uyaphumelela.\nSebenzisa izinkinobho 1-6 ukukhetha umgodi. Cindezela u-E ukuhlola ibhodi.",
},
}
# fmt: on


def generate_ftl(locale: str, t: dict) -> str:
    return f"""# Mancala game messages — {locale}
# Note: Common messages like round-start, turn-start are in games.ftl

# Game info
game-name-mancala = {t["game-name"]}

# Actions
mancala-pit-label = {t["pit-label"]}

# Game events
mancala-sow = {t["sow"]}
mancala-capture = {t["capture"]}
mancala-extra-turn = {t["extra-turn"]}
mancala-winner = {t["winner"]}
mancala-draw = {t["draw"]}

# Board status
mancala-board-status =
    {t["board-status"]}

# Options
mancala-set-stones = {t["set-stones"]}
mancala-desc-stones = {t["desc-stones"]}
mancala-enter-stones = {t["enter-stones"]}
mancala-option-changed-stones = {t["option-changed-stones"]}

# Disabled reasons
mancala-pit-empty = {t["pit-empty"]}

# Rules
mancala-rules =
    {chr(10).join("    " + line if i > 0 else line for i, line in enumerate(t["rules"].split(chr(10))))}

# End screen
mancala-final-score = {t["final-score"]}
"""


def main():
    for locale, translations in TRANSLATIONS.items():
        path = LOCALES_DIR / locale / "mancala.ftl"
        content = generate_ftl(locale, translations)
        path.write_text(content, encoding="utf-8")
        print(f"  Wrote {locale}/mancala.ftl")
    print(f"\nTranslated {len(TRANSLATIONS)} locales.")


if __name__ == "__main__":
    main()
